version: "2.4"

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
  mongo:
    container_name: jabberish-db
    image: mongo
    ports:
      - "27027:27027"
